# This is a basic workflow to help you get started with Actions

name: copy to dbbact-calour-core

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # copy the repo without the big ontology data files
  copy_to_core:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: list files in dir
        run: ls

      - name: delete additional ontology files
        run: find dbbact_calour/data/ -type f -not -name 'other.ontology.*' -delete

      - name: delete github actions (we don't want recursive)
        run: rm -r .github/workflows

      - name: Pushes to another repository
        id: push_directory
        uses: amnona/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '.'
          destination-github-username: 'amnona'
          destination-repository-name: 'dbbact-calour-core'
          target-branch: main
          user-email: amnonim@gmail.com
          commit-message: See ORIGIN_COMMIT
